### PR TITLE
Add Guide on how to migrate code from Objective-C to Swift

### PR DESCRIPTION
**Pull request by Hollister009**
Need the labels

### CODE REVIEW

**Comment by Hollister009** [comment]
Resulted from: https://github.com/ekreative/react-native-braintree/issues/55#issuecomment-1784745607

**Comment by Hollister009** [comment]
@vasylnahuliak  I think I can try to rewrite the existing code from Objective-C to Swift

**Comment by vasylnahuliak** [comment]
Incredible work! Thank you a ton.

**Comment by vasylnahuliak** [comment]
> @vasylnahuliak I think I can try to rewrite the existing code from Objective-C to Swift

Feel free to create a new pull request with the code.

**Pull request merged**
